# Generated by Django 5.0.7 on 2026-04-21 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('UI Designer', 'UI Designer'), ('UX Designer', 'UX Designer'), ('Product Manager', 'Product Manager'), ('Developer', 'Developer'), ('Business Analyst', 'Business Analyst'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Executive', 'Executive'), ('Other', 'Other')], help_text="User's professional role", max_length=100, null=True)),
                ('industry', models.CharField(blank=True, choices=[('Design', 'Design'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Hospitality', 'Hospitality'), ('Other', 'Other')], help_text='Industry user works in', max_length=100, null=True)),
                ('interest', models.CharField(blank=True, help_text="User's primary interest", max_length=255, null=True)),
                ('budget', models.FloatField(blank=True, help_text='Budget in currency', null=True)),
                ('location_city', models.CharField(blank=True, help_text='City where user is located', max_length=100, null=True)),
                ('location_country', models.CharField(blank=True, help_text='Country where user is located', max_length=100, null=True)),
                ('linkedin_text', models.TextField(blank=True, help_text='LinkedIn bio or professional summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'bleisure_user_profile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='bleisure_us_user_id_faeb4e_idx')],
            },
        ),
    ]
