# Generated by Django 5.2.13 on 2026-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleisure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Conference title', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly slug auto-generated from title', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the conference', null=True)),
                ('start_date', models.DateField(help_text='Conference start date')),
                ('end_date', models.DateField(help_text='Conference end date')),
                ('city', models.CharField(db_index=True, help_text='City where conference is held', max_length=100)),
                ('country', models.CharField(help_text='Country where conference is held', max_length=100)),
                ('venue', models.CharField(blank=True, help_text='Venue/location details', max_length=255, null=True)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone of the conference', max_length=50)),
                ('rating', models.FloatField(default=0.0, help_text='Conference rating (0-5)')),
                ('interested_count', models.IntegerField(default=0, help_text='Number of users interested in this conference')),
                ('source', models.CharField(blank=True, help_text="Source of conference information (e.g., 'EventBrite', 'LinkedIn')", max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, help_text='URL of the conference source', max_length=500, null=True, unique=True)),
                ('hash', models.CharField(blank=True, help_text='Hash for deduplication', max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this conference is active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'db_table': 'bleisure_conference',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='bleisure_co_created_6e615c_idx'), models.Index(fields=['city'], name='bleisure_co_city_60cb73_idx'), models.Index(fields=['start_date'], name='bleisure_co_start_d_1dd8b9_idx'), models.Index(fields=['is_active', '-created_at'], name='bleisure_co_is_acti_f7975f_idx'), models.Index(fields=['city', 'start_date'], name='bleisure_co_city_ff5a44_idx')],
            },
        ),
    ]
