# Generated by Django 5.2.13 on 2026-04-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleisure', '0002_conference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConferenceInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When user marked interest')),
                ('conference', models.ForeignKey(help_text='Conference the user is interested in', on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='bleisure.conference')),
                ('user', models.ForeignKey(help_text='User who marked interest', on_delete=django.db.models.deletion.CASCADE, related_name='conference_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Conference Interest',
                'verbose_name_plural': 'User Conference Interests',
                'db_table': 'bleisure_user_conference_interest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='bleisure_us_user_id_79d105_idx'), models.Index(fields=['conference'], name='bleisure_us_confere_fe9778_idx'), models.Index(fields=['user', 'conference'], name='bleisure_us_user_id_ec4438_idx')],
                'unique_together': {('user', 'conference')},
            },
        ),
        migrations.CreateModel(
            name='UserConferenceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(help_text='Rating value (0-5 stars)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When rating was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When rating was last updated')),
                ('conference', models.ForeignKey(help_text='Conference being rated', on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='bleisure.conference')),
                ('user', models.ForeignKey(help_text='User who submitted the rating', on_delete=django.db.models.deletion.CASCADE, related_name='conference_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Conference Rating',
                'verbose_name_plural': 'User Conference Ratings',
                'db_table': 'bleisure_user_conference_rating',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='bleisure_us_user_id_878847_idx'), models.Index(fields=['conference'], name='bleisure_us_confere_140ce0_idx'), models.Index(fields=['user', 'conference'], name='bleisure_us_user_id_3f9e99_idx')],
                'unique_together': {('user', 'conference')},
            },
        ),
    ]
