# Generated by Django 5.2.13 on 2026-04-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bleisure', '0004_event_model_refactor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='bleisure_ev_created_2dbdfe_idx',
            old_name='bleisure_ev_created_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='bleisure_ev_city_279fbf_idx',
            old_name='bleisure_ev_city_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='bleisure_ev_type_a6c565_idx',
            old_name='bleisure_ev_type_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='bleisure_ev_start_d_7f517b_idx',
            old_name='bleisure_ev_start_d_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='bleisure_ev_is_acti_7031ea_idx',
            old_name='bleisure_ev_is_acti_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='bleisure_ev_city_253764_idx',
            old_name='bleisure_ev_city_st_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='subevent',
            new_name='bleisure_su_event_i_cbdb39_idx',
            old_name='bleisure_su_event_i_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='subevent',
            new_name='bleisure_su_start_t_359af5_idx',
            old_name='bleisure_su_start_t_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='usereventinterest',
            new_name='bleisure_us_user_id_2f4228_idx',
            old_name='bleisure_us_user_id_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='usereventinterest',
            new_name='bleisure_us_event_i_8389bf_idx',
            old_name='bleisure_us_event_i_xxxxx_idx',
        ),
        migrations.RenameIndex(
            model_name='usereventinterest',
            new_name='bleisure_us_user_id_9ac45b_idx',
            old_name='bleisure_us_user_id_xxxxx_2_idx',
        ),
        migrations.RenameIndex(
            model_name='usereventreview',
            new_name='bleisure_us_user_id_dff93a_idx',
            old_name='bleisure_us_user_id_xxxxx_3_idx',
        ),
        migrations.RenameIndex(
            model_name='usereventreview',
            new_name='bleisure_us_event_i_0e4440_idx',
            old_name='bleisure_us_event_i_xxxxx_2_idx',
        ),
        migrations.RenameIndex(
            model_name='usereventreview',
            new_name='bleisure_us_user_id_e1f01d_idx',
            old_name='bleisure_us_user_id_xxxxx_3_2_idx',
        ),
    ]
