# Generated by Django 5.2.13 on 2026-04-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleisure', '0005_rename_bleisure_ev_created_xxxxx_idx_bleisure_ev_created_2dbdfe_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Deal title', max_length=255)),
                ('description', models.TextField(help_text='Deal description')),
                ('discount_percentage', models.FloatField(blank=True, help_text='Discount percentage (0-100)', null=True)),
                ('discount_amount', models.FloatField(blank=True, help_text='Fixed discount amount', null=True)),
                ('code', models.CharField(blank=True, help_text='Discount/promo code', max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Deal expiry date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the deal is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'bleisure_deal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exhibitor/company name', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Exhibitor website URL', null=True)),
                ('description', models.TextField(blank=True, help_text='Company/exhibitor description', null=True)),
                ('booth_number', models.CharField(blank=True, help_text='Booth number at event', max_length=50, null=True)),
                ('logo', models.URLField(blank=True, help_text='Exhibitor logo URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exhibitor',
                'verbose_name_plural': 'Exhibitors',
                'db_table': 'bleisure_exhibitor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Speaker's full name", max_length=255)),
                ('company', models.CharField(blank=True, help_text='Company the speaker works at', max_length=255, null=True)),
                ('designation', models.CharField(blank=True, help_text="Speaker's job title/designation", max_length=255, null=True)),
                ('bio', models.TextField(blank=True, help_text='Speaker biography', null=True)),
                ('profile_image', models.URLField(blank=True, help_text="Speaker's profile image URL", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'bleisure_speaker',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='usereventreview',
            name='review_text',
            field=models.TextField(blank=True, help_text='Detailed review text', null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_url'], name='bleisure_ev_source__96746f_idx'),
        ),
        migrations.AddField(
            model_name='deal',
            name='event',
            field=models.ForeignKey(help_text='Event associated with this deal', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='bleisure.event'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='event',
            field=models.ForeignKey(help_text='Event where exhibitor is participating', on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='bleisure.event'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(help_text='Event where speaker is presenting', on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='bleisure.event'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['event'], name='bleisure_de_event_i_68479a_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_active'], name='bleisure_de_is_acti_b4723e_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expiry_date'], name='bleisure_de_expiry__578459_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibitor',
            index=models.Index(fields=['event'], name='bleisure_ex_event_i_e2f3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibitor',
            index=models.Index(fields=['name'], name='bleisure_ex_name_4b1453_idx'),
        ),
        migrations.AddIndex(
            model_name='speaker',
            index=models.Index(fields=['event'], name='bleisure_sp_event_i_3b03ce_idx'),
        ),
        migrations.AddIndex(
            model_name='speaker',
            index=models.Index(fields=['name'], name='bleisure_sp_name_7966cb_idx'),
        ),
    ]
