# Generated by Django 5.2.13 on 2026-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleisure', '0006_add_speaker_exhibitor_deal_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subevent',
            index=models.Index(fields=['event', 'type'], name='bleisure_su_event_i_87b660_idx'),
        ),
    ]
