# Generated by Django 5.2.13 on 2026-04-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleisure', '0007_add_subevent_composite_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL (live stream, registration link, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='subevent',
            name='speaker',
            field=models.ForeignKey(blank=True, help_text='Speaker for this sub-event (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_events', to='bleisure.speaker'),
        ),
    ]
